### ISSUE TITLE
how to import to my project? not able to configure

### ISSUE THREAD

**Issue by saryuvc** [MhdFeras/cordova-plugin-image-recognition#1]
Hello, I want app to detect the object form camera and automatically capture the image.is this plugin provide this functionality? yes then how to import this plugin to my component

**Comment by MhdFeras** [comment]
Hi, saryuvc
This plugin is for recognizing predefined images, it can detect and recognize images automatically without capture the image just aim the camera toward the object which contain the image and the plugin will recognize the image and return the name of it in a success callback
for example you can detect images from books or cards

I explained how to use it in [README.md](https://github.com/MhdFeras/cordova-plugin-image-recognition/blob/master/README.md)

please provide me with more information if you encounter any problem with implementation ... and what platform you are using ?

**Comment by saryuvc** [comment]
Hi,thank you for reply.
I'm using Ionic.
the ionic version is  4.2.0 and Cordova  8.0.0.

**Comment by MhdFeras** [comment]
what is the problem ??

do you fallow the instruction here [get started](https://github.com/MhdFeras/cordova-plugin-image-recognition/blob/master/README.md#get-started) ?

all you need to do is :
- download the plugin `ionic cordova plugin add cordova-plugin-image-recognition`
- generate EasyAR SDK License Key from [https://www.easyar.com/](url)
- use the license key in your code & define the images you need to recognize 

I need more information to be able to help you
any way I'll test the plugin with ionic 4 as soon as possible.

**Comment by saryuvc** [comment]
Hello,

I have implemented the code as u have described in the 'get started'.also generated the key from 'easyar.com' and added to the init method.but the problem is,window does not have 'ImageRecognition' property.and does not allow me to add as window property.
so i want ask that is there any root package i have to add to import it from like 

'import { Camera, CameraOptions } from "@ionic-native/camera";' 

to access the camera i have to import the camera from @ionic-native/camera

i hope you understand my concern.

All i have implemented is:
 platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      
      window.ImageRecognition.init("dufip1XVoIDPtUbpIJpNXJLYeZm7TaL7kZQ6C37z9L5L7ZiT7EJ0aylppDAM1dUvyis8IfGljXrP3pLK0FOI2WAVzIiDKWeyADFI19cd4d5f62967ff2539f2ac63690711d1rnOvJ7cmWcAywqhPBSHkKUgGuBNrhDrjEQWjaBBrgFDxJbgLuQxixAZ3kbWUQIu2neh");

    
      window.ImageRecognition.start().then(data =>{
        console.log('data =>',data)
      },error =>{
        console.log('data =>',JSON.stringify(error))
      });

      statusBar.styleDefault();
      splashScreen.hide();
    });
  }

**Comment by MhdFeras** [comment]
Hi, saryuvc 

you are right .. I tested the plugin with IONIC 4
and I got this error when I build the project
> Property 'ImageRecognition' does not exist on type 'Window'.

ImageRecognition is already existed in window, but the problem is that there is no typescript definition for it.

For now you can call  ImageRecognition as array property
Because typescript doesn't check if array properties are defined on initial build so it safely passes inspection.

It will work like in the code below :
`window['ImageRecognition'].init("XXXXXXXXXX")`

In order to solve the problem definitively i'll add typescript definition to the plugin as soon as possible.

**Comment by saryuvc** [comment]
Ok,i'll try it

Thank you

**Comment by saryuvc** [comment]
Hello MhdFeras,

Still the window does not have ImageRecognition property. so i'm getting the same method,
Even i have console the window object but still can't find ImageRecognition  property.

**Comment by MhdFeras** [comment]
I assumes that you are testing your app on browser !?
if so the ImageRecognition wouldn't be added to window until you run the app on android device.
