### ISSUE TITLE
plugin not compatible with cordova android >= 7.0.0

### ISSUE THREAD

**Issue by tobika** [MhdFeras/cordova-plugin-image-recognition#2]
Just for information, the file structure of the android platform changed since >= 7.0.0 and some files are not copied correctly.

A simple workaround is to stay with cordova android 6.4.0.

Kudos for the plugin, it works really well and helped me a lot in my current project so thanks to the maintainer :)

**Comment by MhdFeras** [comment]
I'm grateful that it helps in your project ^_^
I will make the necessary change to make it compatible with cordova 7.0.0 soon

**Comment by tobika** [comment]
just for info, I didn't retry this with your plugin but had the same error with another cordova plugin, after updating to cordova android 7.1.1 and re-adding the android platform this was resolved

So it might not even be a problem with your plugin

**Comment by MhdFeras** [comment]
Thank you for the feed back 
and sorry for my late response.
