### ISSUE TITLE
Add image from server 

### ISSUE THREAD

**Issue by ganesh8184** [MhdFeras/cordova-plugin-image-recognition#5]
This plugin recognises images from www folder , but i am trying to fetch image from server and adding it for recognition. It is not working
Please help

**Comment by MhdFeras** [comment]
Do you mean fetch images from server to internal storage then adding them for recognition?

if so i think you can do that by removing "www/" form this line 
https://github.com/MhdFeras/cordova-plugin-image-recognition/blob/60f870a726bcf86f90462d460e5aa28bae6aefb0/www/ImageRecognition.js#L68
and when you add images write the full path

i didn't try to read images from internal storage ... but i think it will work.

**Comment by ganesh8184** [comment]
I am directly adding server image url, not fetching to internal storage.
like,

 `window.ImageRecognition.addImage("http://99-604-99-605.com/uploads/logo.png","logo");`

**Comment by ganesh8184** [comment]
> I am directly adding server image url, not fetching to internal storage.
> like,
> 
> `window.ImageRecognition.addImage("http://99-604-99-605.com/uploads/logo.png","logo");`

Is there any solution for it
I am trying to read images directly from server

**Comment by MhdFeras** [comment]
No, you can't load image over http protocol

if you want to load images form server, you can use "EasyAR CRS" it is a cloud service for image recognition
You can manage targets online and change those targets on demand. You can recognize those image targets using SDK API, and get the target meta data from cloud. EasyAR CRS is a paid service, you can get pricing and payment details from [here](https://www.easyar.com/view/crs.html). And you can have a free trial before payment

but you have to make changes on this plugin or create new one to load images from server

I think there is a sample Android code show you how to implement EasyAR CRS
https://s3-us-west-2.amazonaws.com/easyar/sdk/EasyAR_SDK_2.3.0_Basic_Samples_Android_2018-10-24.zip

or you can use this :
https://catchoom.com/image-recognition/
they have plugin for Cordova and you can add images from server
but their pricing is too expensive .. that's why I create this plugin

**Comment by ganesh8184** [comment]
thank you so much!!!!

**Comment by ganesh8184** [comment]
> Do you mean fetch images from server to internal storage then adding them for recognition?
> 
> if so i think you can do that by removing "www/" form this line
> [cordova-plugin-image-recognition/www/ImageRecognition.js](https://github.com/MhdFeras/cordova-plugin-image-recognition/blob/60f870a726bcf86f90462d460e5aa28bae6aefb0/www/ImageRecognition.js#L68)
> 
> Line 68 in [60f870a](/MhdFeras/cordova-plugin-image-recognition/commit/60f870a726bcf86f90462d460e5aa28bae6aefb0)
> 
>  _data.images.push({"image": "www/"+image,"name":name}); 
> 
> and when you add images write the full path
> i didn't try to read images from internal storage ... but i think it will work.

It is also not reading file path from internal storage 
is there any way to resolve it

**Comment by ganesh8184** [comment]
> Do you mean fetch images from server to internal storage then adding them for recognition?
> 
> if so i think you can do that by removing "www/" form this line
> [cordova-plugin-image-recognition/www/ImageRecognition.js](https://github.com/MhdFeras/cordova-plugin-image-recognition/blob/60f870a726bcf86f90462d460e5aa28bae6aefb0/www/ImageRecognition.js#L68)
> 
> Line 68 in [60f870a](/MhdFeras/cordova-plugin-image-recognition/commit/60f870a726bcf86f90462d460e5aa28bae6aefb0)
> 
>  _data.images.push({"image": "www/"+image,"name":name}); 
> 
> and when you add images write the full path
> i didn't try to read images from internal storage ... but i think it will work.

we can add image from internal storage, we have to change code in HelloAR.java 

`private void loadFromImage(ImageTracker tracker, String path , String name)
    {
        ImageTarget target = new ImageTarget();
        String jstr = "{\n"
            + "  \"images\" :\n"
            + "  [\n"
            + "    {\n"
            + "      \"image\" : \"" + path + "\",\n"
            + "      \"name\" : \"" + name + "\"\n"
            + "    }\n"
            + "  ]\n"
            + "}";
        target.setup(jstr, StorageType.Absolute | StorageType.Json , name);
        tracker.loadTarget(target, new FunctorOfVoidFromPointerOfTargetAndBool() {
            @Override
            public void invoke(Target target, boolean status) {
                Log.i("ImageRecognition", String.format("loadFromImage target (%b): %s (%d)", status, target.name(), target.runtimeID()));
            }
        });
    }`

change Assets to Absolute in storagetype

and pass image absolute path from internal storage like

`storage/emulated/0/Android/data/com.image.pro/files/1590.jpg`
